import CSDL2

let scanCodeMask:Uint32 = 1<<30

@inline(__always) 
private func scanCodeToKeyCode(_ code: UInt32) -> Int {
    return Int(code | scanCodeMask)
}

public struct KeyCode: OptionSet {
    public let rawValue : Int
    public init(rawValue: Int) {
        self.rawValue = rawValue
    }

    public static let `return`    = KeyCode(rawValue: Int(SDLK_RETURN.rawValue))
    public static let escape      = KeyCode(rawValue: Int(SDLK_ESCAPE.rawValue))
    public static let backspace   = KeyCode(rawValue: Int(SDLK_BACKSPACE.rawValue))
    public static let tab         = KeyCode(rawValue: Int(SDLK_TAB.rawValue))
    public static let space       = KeyCode(rawValue: Int(SDLK_SPACE.rawValue))
    public static let exclamation = KeyCode(rawValue: Int(SDLK_EXCLAIM.rawValue))
    public static let doubleQuote = KeyCode(rawValue: Int(SDLK_QUOTEDBL.rawValue))
    public static let hash        = KeyCode(rawValue: Int(SDLK_HASH.rawValue))
    public static let percent     = KeyCode(rawValue: Int(SDLK_PERCENT.rawValue))
    public static let dollar      = KeyCode(rawValue: Int(SDLK_DOLLAR.rawValue))
    public static let ampersand   = KeyCode(rawValue: Int(SDLK_AMPERSAND.rawValue))
    public static let singleQuote = KeyCode(rawValue: Int(SDLK_QUOTE.rawValue))
    public static let leftParen   = KeyCode(rawValue: Int(SDLK_LEFTPAREN.rawValue))
    public static let rightParen  = KeyCode(rawValue: Int(SDLK_RIGHTPAREN.rawValue))
    public static let asterix     = KeyCode(rawValue: Int(SDLK_ASTERISK.rawValue))
    public static let plus        = KeyCode(rawValue: Int(SDLK_PLUS.rawValue))
    public static let comma       = KeyCode(rawValue: Int(SDLK_COMMA.rawValue))
    public static let minus       = KeyCode(rawValue: Int(SDLK_MINUS.rawValue))
    public static let period      = KeyCode(rawValue: Int(SDLK_PERIOD.rawValue))
    public static let slash       = KeyCode(rawValue: Int(SDLK_SLASH.rawValue))

    public static let zero  = KeyCode(rawValue: Int(SDLK_0.rawValue))
    public static let one   = KeyCode(rawValue: Int(SDLK_1.rawValue))
    public static let two   = KeyCode(rawValue: Int(SDLK_2.rawValue))
    public static let three = KeyCode(rawValue: Int(SDLK_3.rawValue))
    public static let four  = KeyCode(rawValue: Int(SDLK_4.rawValue))
    public static let five  = KeyCode(rawValue: Int(SDLK_5.rawValue))
    public static let six   = KeyCode(rawValue: Int(SDLK_6.rawValue))
    public static let seven = KeyCode(rawValue: Int(SDLK_7.rawValue))
    public static let nine  = KeyCode(rawValue: Int(SDLK_9.rawValue))

    public static let colon        = KeyCode(rawValue: Int(SDLK_COLON.rawValue))
    public static let semiColon    = KeyCode(rawValue: Int(SDLK_SEMICOLON.rawValue))
    public static let lessThan     = KeyCode(rawValue: Int(SDLK_LESS.rawValue))
    public static let equals       = KeyCode(rawValue: Int(SDLK_EQUALS.rawValue))
    public static let greaterThan  = KeyCode(rawValue: Int(SDLK_GREATER.rawValue))
    public static let questionMark = KeyCode(rawValue: Int(SDLK_QUESTION.rawValue))
    public static let at           = KeyCode(rawValue: Int(SDLK_AT.rawValue))
    public static let leftBracket  = KeyCode(rawValue:Int(SDLK_LEFTBRACKET.rawValue))
    public static let backslash    = KeyCode(rawValue:Int(SDLK_BACKSLASH.rawValue))
    public static let rightBracket = KeyCode(rawValue:Int(SDLK_RIGHTBRACKET.rawValue))
    public static let caret        = KeyCode(rawValue:Int(SDLK_CARET.rawValue))
    public static let underscore   = KeyCode(rawValue:Int(SDLK_UNDERSCORE.rawValue))
    public static let backquote    = KeyCode(rawValue:Int(SDLK_BACKQUOTE.rawValue))

    public static let A = KeyCode(rawValue:Int(SDLK_a.rawValue))
    public static let B = KeyCode(rawValue:Int(SDLK_b.rawValue))
    public static let C = KeyCode(rawValue:Int(SDLK_c.rawValue))
    public static let D = KeyCode(rawValue:Int(SDLK_d.rawValue))
    public static let E = KeyCode(rawValue:Int(SDLK_e.rawValue))
    public static let F = KeyCode(rawValue:Int(SDLK_f.rawValue))
    public static let G = KeyCode(rawValue:Int(SDLK_g.rawValue))
    public static let H = KeyCode(rawValue:Int(SDLK_h.rawValue))
    public static let I = KeyCode(rawValue:Int(SDLK_i.rawValue))
    public static let J = KeyCode(rawValue:Int(SDLK_j.rawValue))
    public static let K = KeyCode(rawValue:Int(SDLK_k.rawValue))
    public static let L = KeyCode(rawValue:Int(SDLK_l.rawValue))
    public static let M = KeyCode(rawValue:Int(SDLK_m.rawValue))
    public static let N = KeyCode(rawValue:Int(SDLK_n.rawValue))
    public static let O = KeyCode(rawValue:Int(SDLK_o.rawValue))
    public static let P = KeyCode(rawValue:Int(SDLK_p.rawValue))
    public static let Q = KeyCode(rawValue:Int(SDLK_q.rawValue))
    public static let R = KeyCode(rawValue:Int(SDLK_r.rawValue))
    public static let S = KeyCode(rawValue:Int(SDLK_s.rawValue))
    public static let T = KeyCode(rawValue:Int(SDLK_t.rawValue))
    public static let U = KeyCode(rawValue:Int(SDLK_u.rawValue))
    public static let V = KeyCode(rawValue:Int(SDLK_v.rawValue))
    public static let W = KeyCode(rawValue:Int(SDLK_w.rawValue))
    public static let X = KeyCode(rawValue:Int(SDLK_x.rawValue))
    public static let Y = KeyCode(rawValue:Int(SDLK_y.rawValue))
    public static let Z = KeyCode(rawValue:Int(SDLK_z.rawValue))

    public static let capsLock = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_CAPSLOCK.rawValue))

    public static let F1  = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_F1.rawValue))
    public static let F2  = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_F2.rawValue))
    public static let F3  = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_F3.rawValue))
    public static let F4  = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_F4.rawValue))
    public static let F5  = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_F5.rawValue))
    public static let F6  = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_F6.rawValue))
    public static let F7  = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_F7.rawValue))
    public static let F8  = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_F8.rawValue))
    public static let F9  = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_F9.rawValue))
    public static let F10 = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_F10.rawValue))
    public static let F11 = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_F11.rawValue))
    public static let F12 = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_F12.rawValue))

    public static let printScreen = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_PRINTSCREEN.rawValue))
    public static let scrollLock  = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_SCROLLLOCK.rawValue))
    public static let pause       = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_PAUSE.rawValue))
    public static let insert      = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_INSERT.rawValue))
    public static let home        = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_HOME.rawValue))
    public static let pageUp      = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_PAGEUP.rawValue))
    public static let delete      = KeyCode(rawValue:Int(SDLK_DELETE.rawValue))
    public static let end         = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_END.rawValue))
    public static let pageDown    = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_PAGEDOWN.rawValue))
    public static let right       = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_RIGHT.rawValue))
    public static let left        = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_LEFT.rawValue))
    public static let down        = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_DOWN.rawValue))
    public static let up          = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_UP.rawValue))

// TODO: Finish renaming
    public static let numLockClear      = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_NUMLOCKCLEAR.rawValue))
    public static let keyPadDivide      = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_DIVIDE.rawValue))
    public static let keyPadMultiply    = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_MULTIPLY.rawValue))
    public static let keyPadMinus       = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_MINUS.rawValue))
    public static let keyPadPlus        = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_PLUS.rawValue))
    public static let keyPadEnter       = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_ENTER.rawValue))
    public static let keyPad1           = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_1.rawValue))
    public static let keyPad2           = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_2.rawValue))
    public static let keyPad3           = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_3.rawValue))
    public static let keyPad4           = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_4.rawValue))
    public static let keyPad5           = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_5.rawValue))
    public static let keyPad6           = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_6.rawValue))
    public static let keyPad7           = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_7.rawValue))
    public static let keyPad8           = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_8.rawValue))
    public static let keyPad9           = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_9.rawValue))
    public static let keyPad0           = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_0.rawValue))
    public static let keyPadPeriod      = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_PERIOD.rawValue))
    public static let keyPadEquals      = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_EQUALS.rawValue))
    public static let keyPadComma       = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_COMMA.rawValue))
    public static let keyPadEqualsAs400 = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_EQUALSAS400.rawValue))

    public static let Application = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_APPLICATION.rawValue))
    public static let Power       = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_POWER.rawValue))
    public static let F13         = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_F13.rawValue))
    public static let F14         = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_F14.rawValue))
    public static let F15         = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_F15.rawValue))
    public static let F16         = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_F16.rawValue))
    public static let F17         = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_F17.rawValue))
    public static let F18         = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_F18.rawValue))
    public static let F19         = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_F19.rawValue))
    public static let F20         = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_F20.rawValue))
    public static let F21         = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_F21.rawValue))
    public static let F22         = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_F22.rawValue))
    public static let F23         = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_F23.rawValue))
    public static let F24         = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_F24.rawValue))
    public static let execute     = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_EXECUTE.rawValue))
    public static let help        = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_HELP.rawValue))
    public static let menu        = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_MENU.rawValue))
    public static let select      = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_SELECT.rawValue))
    public static let stop        = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_STOP.rawValue))
    public static let again       = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_AGAIN.rawValue))
    public static let undo        = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_UNDO.rawValue))
    public static let cut         = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_CUT.rawValue))
    public static let copy        = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_COPY.rawValue))
    public static let paste       = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_PASTE.rawValue))
    public static let find        = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_FIND.rawValue))
    public static let mute        = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_MUTE.rawValue))
    public static let volumeUp    = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_VOLUMEUP.rawValue))
    public static let volumeDown  = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_VOLUMEDOWN.rawValue))


    public static let alterase   = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_ALTERASE.rawValue))
    public static let sysreq     = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_SYSREQ.rawValue))
    public static let cancel     = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_CANCEL.rawValue))
    public static let clear      = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_CLEAR.rawValue))
    public static let prior      = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_PRIOR.rawValue))
    public static let return2    = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_RETURN2.rawValue))
    public static let separator  = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_SEPARATOR.rawValue))
    public static let out        = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_OUT.rawValue))
    public static let oper       = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_OPER.rawValue))
    public static let clearagain = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_CLEARAGAIN.rawValue))
    public static let crsel      = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_CRSEL.rawValue))
    public static let exsel      = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_EXSEL.rawValue))

    public static let keyPad00                = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_00.rawValue))
    public static let keyPad000               = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_000.rawValue))
    public static let thousandsSeparator      = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_THOUSANDSSEPARATOR.rawValue))
    public static let decimalSeparator        = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_DECIMALSEPARATOR.rawValue))
    public static let currencyUnit            = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_CURRENCYUNIT.rawValue))
    public static let currencySubunit         = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_CURRENCYSUBUNIT.rawValue))
    public static let keyPadLeftParen         = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_LEFTPAREN.rawValue))
    public static let keyPadRightParen        = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_RIGHTPAREN.rawValue))
    public static let keyPadLeftBrace         = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_LEFTBRACE.rawValue))
    public static let keyPadRightBrace        = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_RIGHTBRACE.rawValue))
    public static let keyPadTab               = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_TAB.rawValue))
    public static let keyPadBackspace         = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_BACKSPACE.rawValue))
    public static let keyPadA                 = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_A.rawValue))
    public static let keyPadB                 = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_B.rawValue))
    public static let keyPadC                 = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_C.rawValue))
    public static let keyPadD                 = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_D.rawValue))
    public static let keyPadE                 = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_E.rawValue))
    public static let keyPadF                 = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_F.rawValue))
    public static let keyPadXor               = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_XOR.rawValue))
    public static let keyPadPower             = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_POWER.rawValue))
    public static let keyPadPercentT          = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_PERCENT.rawValue))
    public static let keyPadLess              = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_LESS.rawValue))
    public static let keyPadGreater           = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_GREATER.rawValue))
    public static let keyPadAmpersand         = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_AMPERSAND.rawValue))
    public static let keyPadDoubleAmpersand   = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_DBLAMPERSAND.rawValue))
    public static let keyPadVerticalBar       = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_VERTICALBAR.rawValue))
    public static let keyPadDoubleVerticalBar = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_DBLVERTICALBAR.rawValue))
    public static let keyPadColon             = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_COLON.rawValue))
    public static let keyPadHash              = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_HASH.rawValue))
    public static let keyPadSpace             = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_SPACE.rawValue))
    public static let keyPadAt                = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_AT.rawValue))
    public static let keyPadExclamation       = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_EXCLAM.rawValue))
    public static let keyPadMemStore          = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_MEMSTORE.rawValue))
    public static let keyPadMemRecalL         = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_MEMRECALL.rawValue))
    public static let keyPadMemClear          = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_MEMCLEAR.rawValue))
    public static let keyPadMemAdd            = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_MEMADD.rawValue))
    public static let keyPadMemSubtract       = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_MEMSUBTRACT.rawValue))
    public static let keyPadMemMultiply       = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_MEMMULTIPLY.rawValue))
    public static let keyPadMemDivide         = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_MEMDIVIDE.rawValue))
    public static let keyPadPlusMinus         = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_PLUSMINUS.rawValue))
    public static let keyPadClear             = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_CLEAR.rawValue))
    public static let keyPadClearEntry        = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_CLEARENTRY.rawValue))
    public static let keyPadBinary            = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_BINARY.rawValue))
    public static let keyPadOctal             = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_OCTAL.rawValue))
    public static let keyPadDecimal           = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_DECIMAL.rawValue))
    public static let keyPadHexaDecimal       = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KP_HEXADECIMAL.rawValue))

    public static let leftCtrl   = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_LCTRL.rawValue))
    public static let leftShift  = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_LSHIFT.rawValue))
    public static let leftAlt    = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_LALT.rawValue))
    public static let leftGUI    = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_LGUI.rawValue))
    public static let rightCtrl  = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_RCTRL.rawValue))
    public static let rightShift = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_RSHIFT.rawValue))
    public static let rightAlt   = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_RALT.rawValue))
    public static let rightGUI   = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_RGUI.rawValue))

    public static let mode = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_MODE.rawValue))

    public static let audioNext   = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_AUDIONEXT.rawValue))
    public static let audioPrev   = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_AUDIOPREV.rawValue))
    public static let audioStop   = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_AUDIOSTOP.rawValue))
    public static let audioPlay   = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_AUDIOPLAY.rawValue))
    public static let audioMute   = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_AUDIOMUTE.rawValue))
    public static let mediaSelect = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_MEDIASELECT.rawValue))
    public static let www         = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_WWW.rawValue))
    public static let mail        = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_MAIL.rawValue))
    public static let calculator  = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_CALCULATOR.rawValue))
    public static let computer    = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_COMPUTER.rawValue))
    public static let acSearch    = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_AC_SEARCH.rawValue))
    public static let acHome      = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_AC_HOME.rawValue))
    public static let acBack      = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_AC_BACK.rawValue))
    public static let acForward   = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_AC_FORWARD.rawValue))
    public static let acStop      = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_AC_STOP.rawValue))
    public static let acRefresh   = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_AC_REFRESH.rawValue))
    public static let acBookmarks = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_AC_BOOKMARKS.rawValue))

    public static let brightnessDown = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_BRIGHTNESSDOWN.rawValue))
    public static let brightnessUp   = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_BRIGHTNESSUP.rawValue))
    public static let displaySwitch  = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_DISPLAYSWITCH.rawValue))
    public static let illumToggle    = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KBDILLUMTOGGLE.rawValue))
    public static let illumDown      = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KBDILLUMDOWN.rawValue))
    public static let illumUp        = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_KBDILLUMUP.rawValue))
    public static let eject          = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_EJECT.rawValue))
    public static let sleep          = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_SLEEP.rawValue))
    public static let app1           = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_APP1.rawValue))
    public static let app2           = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_APP2.rawValue))

    public static let audioRewind      = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_AUDIOREWIND.rawValue))
    public static let audioFastForward = scanCodeToKeyCode(GlobalInt(SDL_SCANCODE_AUDIOFASTFORWARD.rawValue))
}

public struct KeyMod: OptionSet {
    public let rawValue : UInt32
    public init(rawValue: UInt32) {
        self.rawValue = rawValue
    }

    public static let none       = KeyMod(rawValue: GlobalInt(KMOD_NONE.rawValue))
    public static let leftShift  = KeyMod(rawValue: GlobalInt(KMOD_LSHIFT.rawValue))
    public static let rightShift = KeyMod(rawValue: GlobalInt(KMOD_RSHIFT.rawValue))
    public static let leftCtrl   = KeyMod(rawValue: GlobalInt(KMOD_LCTRL.rawValue))
    public static let rightCtrl  = KeyMod(rawValue: GlobalInt(KMOD_RCTRL.rawValue))
    public static let leftAlt    = KeyMod(rawValue: GlobalInt(KMOD_LALT.rawValue))
    public static let rightAlt   = KeyMod(rawValue: GlobalInt(KMOD_RALT.rawValue))
    public static let leftGUI    = KeyMod(rawValue: GlobalInt(KMOD_LGUI.rawValue))
    public static let rightGUI   = KeyMod(rawValue: GlobalInt(KMOD_RGUI.rawValue))
    public static let numLock    = KeyMod(rawValue: GlobalInt(KMOD_NUM.rawValue))
    public static let capsLock   = KeyMod(rawValue: GlobalInt(KMOD_CAPS.rawValue))
    public static let mode       = KeyMod(rawValue: GlobalInt(KMOD_MODE.rawValue))
    public static let reserved   = KeyMod(rawValue: GlobalInt(KMOD_RESERVED.rawValue))
    
    public static let ctrl       = KeyMod(rawValue: GlobalInt(KMOD_LCTRL.rawValue | KMOD_RCTRL.rawValue))
    public static let shift      = KeyMod(rawValue: GlobalInt(KMOD_LSHIFT.rawValue | KMOD_RSHIFT.rawValue))
    public static let alt        = KeyMod(rawValue: GlobalInt(KMOD_LALT.rawValue | KMOD_RALT.rawValue))
    public static let GUI        = KeyMod(rawValue: GlobalInt(KMOD_LGUI.rawValue | KMOD_RGUI.rawValue))

}

